//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclarationDeVol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Declaration
    {
        public int declaration_id { get; set; }
        [DisplayName("Déclarant")]
        public Nullable<int> user_id { get; set; }
        [DisplayName("Catégorie objet")]
        public Nullable<int> objectCat_id { get; set; }
        [DisplayName("Nom objet")]
        public string object_name { get; set; }
        [DisplayName("Description objet")]
        public string obj_description { get; set; }
        [DisplayName("Date vol")]
        public System.DateTime vol_date { get; set; }
        [DisplayName("Lieu vol")]
        public string place { get; set; }
        [DisplayName("Date déclaration")]
        public System.DateTime decl_date { get; set; }
        [DisplayName("Rôle déclarant")]
        public string user_role { get; set; }
        [DisplayName("Statut")]
        public Nullable<int> statut { get; set; }
    
        public virtual ObjectCategory ObjectCategory { get; set; }
        public virtual Users Users { get; set; }
    }
}
