//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclarationDeVol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Declaration = new HashSet<Declaration>();
        }
    
        public int id { get; set; }

        [DisplayName("Prénom")]
        public string first_name { get; set; }

        [DisplayName("Nom")]
        public string last_name { get; set; }

        [DisplayName("Adresse e-mail")]
        public string email { get; set; }

        [DisplayName("Téléphone")]
        public string tel { get; set; }

        [DisplayName("Adresse")]
        public string address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Declaration> Declaration { get; set; }
    }
}
